columnSuffix: null
handle: code
instructions: null
name: Code
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
