color: null
fieldLayouts:
  de714725-614c-4d87-8434-c730268052dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 945ed4a6-cde1-42ec-8fe6-1f83a9c33906
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c852384e-4057-40cf-b3cb-32529cde2883
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 57a23b7d-d563-4c33-a795-c53ff1217290
            userCondition: null
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\selectplus\fields\SelectPlusConditionRule
                  fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
                  layoutElementUid: c852384e-4057-40cf-b3cb-32529cde2883
                  operator: in
                  uid: 43c041c0-ac0a-420e-87ab-48a753be66eb
                  values:
                    - addon__alert
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f630a19c-44c3-4d70-9e7c-6db552e8a72d # Bit
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eda2f07b-ee9b-4983-b33c-2db00dd57f2a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\selectplus\fields\SelectPlusConditionRule
                  fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
                  layoutElementUid: c852384e-4057-40cf-b3cb-32529cde2883
                  operator: in
                  uid: a093421b-5ef1-488e-a7b0-e03763c4bd1a
                  values:
                    - addon__modal
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 2ccb2a52-562c-4cc8-ac89-d14784532a6b # Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84c08d60-7039-4fa8-9235-94cf30f26151
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\selectplus\fields\SelectPlusConditionRule
                  fieldUid: 31cc93a2-d38f-4943-b7c2-473b72eb69a1 # Variant
                  layoutElementUid: c852384e-4057-40cf-b3cb-32529cde2883
                  operator: in
                  uid: 534c15d8-5de5-403c-9514-0e6507679387
                  values:
                    - addon__code
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: b24f1298-62ac-4de3-9ac3-32e644553bab # Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fa78d3c-705b-4e06-8bde-109d8ef3a4de
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            template: _sitehub/ui-template-addons.twig
            type: craft\fieldlayoutelements\Template
            uid: 14660f4e-af96-4639-91d6-2bd103b73b9b
            userCondition: null
            width: 50
        name: Content
        uid: 994027a3-c00f-44b1-b208-22de5afd7a86
        userCondition: null
handle: addon
hasTitleField: true
icon: candy
name: Addon
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
