color: null
fieldLayouts:
  b6162b48-2261-437e-a2de-07b767ec2e81:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 99915c91-810f-4ec3-a1f3-3977fde78acf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: b24f1298-62ac-4de3-9ac3-32e644553bab # Code
                  layoutElementUid: c7da2ae7-76e4-45d1-9523-1dc41bf4ce7a
                  operator: empty
                  uid: b2207621-c0e7-4773-aee9-880b6cd76438
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: d554a8e7-e8ad-493b-aaa8-d611bf04b257 # Website / Content URL
            handle: null
            includeInCards: false
            instructions: null
            label: URL
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34c14ce2-99c8-4ece-8121-448e83999375
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: d554a8e7-e8ad-493b-aaa8-d611bf04b257 # Website / Content URL
                  layoutElementUid: 34c14ce2-99c8-4ece-8121-448e83999375
                  operator: empty
                  uid: 6afa79a1-dd24-4f8f-af44-19f6125e9ee9
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: b24f1298-62ac-4de3-9ac3-32e644553bab # Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7da2ae7-76e4-45d1-9523-1dc41bf4ce7a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            template: _sitehub/ui-template-embed.twig
            type: craft\fieldlayoutelements\Template
            uid: 08f839b6-8a55-4149-adde-15b3b080afef
            userCondition: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9d39d677-dcb4-4e47-b3de-914118bf7f01
            userCondition: null
          -
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcf1d856-765b-4e27-88f2-efd3169c577f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34b55bb2-c8e5-4f26-9638-5217cbc85568
            userCondition: null
            warning: null
            width: 50
        name: 'Primary Content'
        uid: 2a8ab943-0b7a-407b-891a-366a3893b58a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics & Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7558aec8-7d83-4ec5-909c-5934d4282f03
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: de613bee-ca00-4da7-8543-8a1e3cf72dba
            userCondition: null
          -
            elementCondition: null
            fieldUid: bdc12ed2-dd0e-4189-9c87-1adaee91e73c # Transcript
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ce44ed6-f623-406f-893d-66c76e5e335c
            userCondition: null
            warning: null
            width: 75
        name: 'Meta Details'
        uid: 624ceb73-0d40-4cfb-873b-dd11262fe5c6
        userCondition: null
handle: embed
hasTitleField: true
icon: anchor
name: Embed
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
